#+BEGIN_EXPORT html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
<title>make-core</title>
  <style type="text/css">
body {
    margin-left: 5%;
    margin-right: 5%;
    font-family: Times, serif;
    font-size: 110%;
}

h1, h2, h3, h4, h5, h6, p {
    font-family: Times, serif;
}

dt {
    font-weight: bold
}

pre {
    font-family: Courier New, monospace;
    font-size: 100%;
    font-weight: bold
}

ins {
    color: green;
}

del {
    color: red;
}

dt {
    font-weight: bold
}

p.red {
    color: red;
}

span.red {
    color: red;
}

div.red {
    color: red;
}

blockquote {
    margin-left: 5%;
    margin-right: 5%;
    font-family: Times, serif;
    font-style: italic;
    text-align: left;
    text-indent: 0px;
}
  </style>
</head>
<body>
#+END_EXPORT
* WP-save-cf7-file-uploads

[[https://img.shields.io/badge/version-VERSION-orange.svg][version]]

[[https://img.shields.io/badge/WordPress-Compatible-blue.svg][WordPress]]

- This plugin adds enhancements to
  [Store file uploads for Contact Form 7](https://wordpress.org/plugins/store-file-uploads-for-contact-form-7/)
  by Mircea N. (version 1.3.0)

** Enhancements

1. Normalize file names. File names can only contain letters in the
   set: [a-zA-Z0-9.-\_]. Convert any letters not in the set to a "\_".
2. Only graphic files are allowed. Skipped files are logged.
3. Avoid overwriting existing files, by appending "\_N" to base name.

** Installation and Usage

See: readme.txt for official install and usage directions.

*** Development Installs

1. Install and activate the Contact Form 7 plugin.
2. Install and activate the Flamingo plugin.
3. Go to: https://moria.whyayh.com/rel/released/software/own/WP-save-cf7-uploads
4. Then download the save-cf7-file-uploads-VER.zip file you want.
5. In WordPress, install with upload plugin, then activate.

In the "Additional Settings" tab for a contact form make sure
"do_not_store:" is not "true"
